/**
 * Tax Invoice PDF — Vietnamese GTGT (VAT 10%) format.
 *
 * v1: manual upload is the canonical path (the office uploads a PDF
 * generated by Viettel's e-invoice portal). This template is used as a
 * fallback preview / draft when no upload exists yet, and as the rendered
 * artifact when an office uploads metadata only (rare).
 *
 * Locale: vi primary (Vietnamese tax compliance). KO + EN render
 * translation copies of labels only — the legal text stays in Vietnamese.
 */

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export type TaxInvoiceLocale = "ko" | "vi" | "en";

export interface TaxInvoicePayload {
  invoiceNumber: string;
  invoiceDate: Date;
  paymentId: string;
  customerName: string;
  customerCode: string;
  taxCode: string | null;
  address: string;
  subtotal: number;
  vatRate: number;
  vatAmount: number;
  total: number;
  description: string;
  locale: TaxInvoiceLocale;
  generatedAt: Date;
}

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#111" },
  brand: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 2,
    borderBottomColor: "#0C6BA8",
    paddingBottom: 8,
    marginBottom: 12,
  },
  brandTitle: { fontSize: 14, fontWeight: "bold", color: "#0C6BA8" },
  brandLegal: { fontSize: 8, color: "#666" },
  docTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 4,
    marginBottom: 4,
    textAlign: "center",
    color: "#0C6BA8",
  },
  subTitle: {
    fontSize: 10,
    marginBottom: 12,
    textAlign: "center",
    color: "#525252",
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  metaCell: { fontSize: 10 },
  card: {
    borderWidth: 1,
    borderColor: "#e5e5e5",
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  row: { flexDirection: "row", marginBottom: 3 },
  label: { width: 130, color: "#666" },
  value: { flex: 1, color: "#111" },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#F0F8FE",
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#0C6BA8",
    marginTop: 14,
    fontWeight: "bold",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
  },
  c1: { flex: 4 },
  c2: { flex: 2, textAlign: "right" },
  totalsBox: {
    marginTop: 14,
    alignSelf: "flex-end",
    width: 240,
  },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
  },
  totalsLabel: { color: "#525252" },
  totalsValue: { color: "#111" },
  grandTotal: {
    marginTop: 4,
    paddingTop: 6,
    borderTopWidth: 2,
    borderTopColor: "#0C6BA8",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  grandTotalValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#0C6BA8",
  },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 36,
    right: 36,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: "#888",
  },
});

interface LabelDict {
  title: string;
  subTitle: string;
  invoiceNo: string;
  invoiceDate: string;
  buyer: string;
  buyerCode: string;
  taxCode: string;
  address: string;
  description: string;
  amount: string;
  subtotal: string;
  vat: string;
  total: string;
  generated: string;
}

const LABELS: Record<TaxInvoiceLocale, LabelDict> = {
  vi: {
    title: "HÓA ĐƠN GIÁ TRỊ GIA TĂNG",
    subTitle: "VAT Invoice — Mẫu số 01GTKT",
    invoiceNo: "Số hóa đơn",
    invoiceDate: "Ngày phát hành",
    buyer: "Người mua",
    buyerCode: "Mã KH",
    taxCode: "MST",
    address: "Địa chỉ",
    description: "Nội dung",
    amount: "Số tiền (VND)",
    subtotal: "Cộng tiền hàng",
    vat: "Thuế GTGT (10%)",
    total: "Tổng cộng",
    generated: "Tạo lúc",
  },
  ko: {
    title: "부가가치세 세금계산서",
    subTitle: "VAT Invoice — 양식 01GTKT",
    invoiceNo: "인보이스 번호",
    invoiceDate: "발행일",
    buyer: "구매자",
    buyerCode: "고객 코드",
    taxCode: "세금 코드",
    address: "주소",
    description: "내용",
    amount: "금액 (VND)",
    subtotal: "공급가액",
    vat: "VAT (10%)",
    total: "합계",
    generated: "발행 시각",
  },
  en: {
    title: "VAT INVOICE",
    subTitle: "Vietnamese GTGT — Form 01GTKT",
    invoiceNo: "Invoice no.",
    invoiceDate: "Issue date",
    buyer: "Buyer",
    buyerCode: "Customer code",
    taxCode: "Tax code",
    address: "Address",
    description: "Description",
    amount: "Amount (VND)",
    subtotal: "Subtotal",
    vat: "VAT (10%)",
    total: "Total",
    generated: "Generated",
  },
};

function formatVnd(n: number): string {
  if (!Number.isFinite(n)) return "0";
  return Math.round(n).toLocaleString("vi-VN");
}

function formatDate(d: Date, locale: TaxInvoiceLocale): string {
  const pad = (x: number) => (x < 10 ? `0${x}` : String(x));
  const yyyy = d.getFullYear();
  const mm = pad(d.getMonth() + 1);
  const dd = pad(d.getDate());
  if (locale === "vi") return `${dd}/${mm}/${yyyy}`;
  return `${yyyy}-${mm}-${dd}`;
}

interface TaxInvoiceProps {
  payload: TaxInvoicePayload;
}

export function TaxInvoiceTemplate({ payload }: Readonly<TaxInvoiceProps>) {
  const L = LABELS[payload.locale];
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.brand}>
          <View>
            <Text style={styles.brandTitle}>SEOUL AQUA</Text>
            <Text style={styles.brandLegal}>
              CÔNG TY TNHH MTV TM&DV ĐẠI Á
            </Text>
            <Text style={styles.brandLegal}>MST: 0312345678</Text>
          </View>
          <View>
            <Text style={styles.brandLegal}>cs@seoulaqua.com.vn</Text>
            <Text style={styles.brandLegal}>+84-28-1234-5678</Text>
          </View>
        </View>

        <Text style={styles.docTitle}>{L.title}</Text>
        <Text style={styles.subTitle}>{L.subTitle}</Text>

        <View style={styles.metaRow}>
          <Text style={styles.metaCell}>
            {L.invoiceNo}: <Text style={{ fontWeight: "bold" }}>{payload.invoiceNumber}</Text>
          </Text>
          <Text style={styles.metaCell}>
            {L.invoiceDate}: {formatDate(payload.invoiceDate, payload.locale)}
          </Text>
        </View>

        <View style={styles.card}>
          <View style={styles.row}>
            <Text style={styles.label}>{L.buyer}:</Text>
            <Text style={styles.value}>{payload.customerName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>{L.buyerCode}:</Text>
            <Text style={styles.value}>{payload.customerCode}</Text>
          </View>
          {payload.taxCode && (
            <View style={styles.row}>
              <Text style={styles.label}>{L.taxCode}:</Text>
              <Text style={styles.value}>{payload.taxCode}</Text>
            </View>
          )}
          {payload.address && (
            <View style={styles.row}>
              <Text style={styles.label}>{L.address}:</Text>
              <Text style={styles.value}>{payload.address}</Text>
            </View>
          )}
        </View>

        <View style={styles.tableHeader}>
          <Text style={styles.c1}>{L.description}</Text>
          <Text style={styles.c2}>{L.amount}</Text>
        </View>
        <View style={styles.tableRow}>
          <Text style={styles.c1}>{payload.description}</Text>
          <Text style={styles.c2}>{formatVnd(payload.subtotal)}</Text>
        </View>

        <View style={styles.totalsBox}>
          <View style={styles.totalsRow}>
            <Text style={styles.totalsLabel}>{L.subtotal}</Text>
            <Text style={styles.totalsValue}>{formatVnd(payload.subtotal)}</Text>
          </View>
          <View style={styles.totalsRow}>
            <Text style={styles.totalsLabel}>{L.vat}</Text>
            <Text style={styles.totalsValue}>{formatVnd(payload.vatAmount)}</Text>
          </View>
          <View style={styles.grandTotal}>
            <Text style={styles.totalsLabel}>{L.total}</Text>
            <Text style={styles.grandTotalValue}>
              {formatVnd(payload.total)} ₫
            </Text>
          </View>
        </View>

        <View style={styles.footer} fixed>
          <Text>
            {L.generated}: {formatDate(payload.generatedAt, payload.locale)}
          </Text>
          <Text>{payload.paymentId.slice(-12).toUpperCase()}</Text>
        </View>
      </Page>
    </Document>
  );
}
